import { Projekt, Einheit, Kunde, Opportunity } from './types';

export const projekte: Projekt[] = [
  {
    id: 'p1',
    name: 'Residenz am Stadtpark',
    ort: 'Leipzig',
    plz: '04109',
    bundesland: 'Sachsen',
    status: 'in_bau',
    fertigstellung: 'Q3 2026',
    energiestandard: 'KfW 55 EE',
    beschreibung: 'Exklusive Wohnanlage mit 24 Einheiten direkt am Stadtpark. Hochwertige Ausstattung, bodentiefe Fenster, Fußbodenheizung. Sehr gute ÖPNV-Anbindung, 5 Minuten bis Innenstadt.',
    einheitenAnzahl: 24,
  },
  {
    id: 'p2',
    name: 'Quartier Westend',
    ort: 'Dresden',
    plz: '01157',
    bundesland: 'Sachsen',
    status: 'in_bau',
    fertigstellung: 'Q1 2027',
    energiestandard: 'KfW 40 NH',
    beschreibung: 'Modernes Stadtquartier mit 36 Einheiten in aufstrebendem Dresdner Westend. Tiefgarage, Concierge-Service, Dachterrasse. Hohe Mietnachfrage durch Nähe zur TU Dresden.',
    einheitenAnzahl: 36,
  },
  {
    id: 'p3',
    name: 'Parkresidenz Gohlis',
    ort: 'Leipzig',
    plz: '04155',
    bundesland: 'Sachsen',
    status: 'planung',
    fertigstellung: 'Q4 2027',
    energiestandard: 'KfW 40 EE',
    beschreibung: 'Stilvolle Neubau-Residenz im grünen Gohlis. 18 Einheiten mit großzügigen Grundrissen, eigenem Gartenanteil (EG), Smart-Home-Vorbereitung.',
    einheitenAnzahl: 18,
  },
];

export const einheiten: Einheit[] = [
  // Projekt 1 – Residenz am Stadtpark
  {
    id: 'e1',
    projektId: 'p1',
    bezeichnung: 'WE 01 – EG links',
    typ: 'wohnung',
    etage: 0,
    zimmer: 2,
    flaeche: 58.4,
    kaufpreis: 218000,
    kaltmiete: 870,
    status: 'verfuegbar',
    balkon: true,
    kfwStandard: 'KfW 55 EE',
    extras: [
      { id: 'ex1', typ: 'tiefgarage', bezeichnung: 'Tiefgaragenstellplatz TG-01', preis: 18500, verfuegbar: true },
      { id: 'ex2', typ: 'keller', bezeichnung: 'Kellerabteil K-01 (6 m²)', preis: 3500, verfuegbar: true },
    ],
  },
  {
    id: 'e2',
    projektId: 'p1',
    bezeichnung: 'WE 02 – EG rechts',
    typ: 'wohnung',
    etage: 0,
    zimmer: 3,
    flaeche: 78.2,
    kaufpreis: 289000,
    kaltmiete: 1100,
    status: 'reserviert',
    reserviertBis: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    reserviertVon: 'Müller Immobilien',
    balkon: false,
    kfwStandard: 'KfW 55 EE',
    extras: [
      { id: 'ex3', typ: 'tiefgarage', bezeichnung: 'Tiefgaragenstellplatz TG-02', preis: 18500, verfuegbar: false },
    ],
  },
  {
    id: 'e3',
    projektId: 'p1',
    bezeichnung: 'WE 03 – 1.OG links',
    typ: 'wohnung',
    etage: 1,
    zimmer: 2,
    flaeche: 61.0,
    kaufpreis: 229000,
    kaltmiete: 920,
    status: 'verfuegbar',
    balkon: true,
    kfwStandard: 'KfW 55 EE',
    extras: [
      { id: 'ex4', typ: 'tiefgarage', bezeichnung: 'Tiefgaragenstellplatz TG-03', preis: 18500, verfuegbar: true },
      { id: 'ex5', typ: 'keller', bezeichnung: 'Kellerabteil K-03 (6 m²)', preis: 3500, verfuegbar: true },
    ],
  },
  {
    id: 'e4',
    projektId: 'p1',
    bezeichnung: 'WE 04 – 1.OG rechts',
    typ: 'wohnung',
    etage: 1,
    zimmer: 4,
    flaeche: 102.5,
    kaufpreis: 378000,
    kaltmiete: 1450,
    status: 'notariell',
    balkon: true,
    kfwStandard: 'KfW 55 EE',
    extras: [],
  },
  {
    id: 'e5',
    projektId: 'p1',
    bezeichnung: 'WE 05 – 2.OG links',
    typ: 'wohnung',
    etage: 2,
    zimmer: 2,
    flaeche: 61.0,
    kaufpreis: 235000,
    kaltmiete: 930,
    status: 'verfuegbar',
    balkon: true,
    kfwStandard: 'KfW 55 EE',
    extras: [
      { id: 'ex6', typ: 'tiefgarage', bezeichnung: 'Tiefgaragenstellplatz TG-05', preis: 18500, verfuegbar: true },
    ],
  },
  {
    id: 'e6',
    projektId: 'p1',
    bezeichnung: 'WE 06 – 2.OG rechts',
    typ: 'wohnung',
    etage: 2,
    zimmer: 3,
    flaeche: 82.0,
    kaufpreis: 305000,
    kaltmiete: 1180,
    status: 'verkauft',
    balkon: true,
    kfwStandard: 'KfW 55 EE',
    extras: [],
  },
  {
    id: 'e7',
    projektId: 'p1',
    bezeichnung: 'WE 07 – DG Penthouse',
    typ: 'wohnung',
    etage: 3,
    zimmer: 4,
    flaeche: 128.0,
    kaufpreis: 498000,
    kaltmiete: 1950,
    status: 'verfuegbar',
    balkon: true,
    kfwStandard: 'KfW 55 EE',
    extras: [
      { id: 'ex7', typ: 'tiefgarage', bezeichnung: 'Tiefgaragenstellplatz TG-07', preis: 21000, verfuegbar: true },
      { id: 'ex8', typ: 'tiefgarage', bezeichnung: 'Tiefgaragenstellplatz TG-08 (2. Platz)', preis: 21000, verfuegbar: true },
    ],
  },
  // Projekt 2 – Quartier Westend
  {
    id: 'e8',
    projektId: 'p2',
    bezeichnung: 'WE A01 – EG',
    typ: 'wohnung',
    etage: 0,
    zimmer: 1,
    flaeche: 38.5,
    kaufpreis: 145000,
    kaltmiete: 590,
    status: 'verfuegbar',
    balkon: false,
    kfwStandard: 'KfW 40 NH',
    extras: [
      { id: 'ex9', typ: 'stellplatz', bezeichnung: 'Außenstellplatz SP-A01', preis: 9500, verfuegbar: true },
    ],
  },
  {
    id: 'e9',
    projektId: 'p2',
    bezeichnung: 'WE A02 – 1.OG',
    typ: 'wohnung',
    etage: 1,
    zimmer: 2,
    flaeche: 56.0,
    kaufpreis: 212000,
    kaltmiete: 850,
    status: 'reserviert',
    reserviertBis: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    reserviertVon: 'Schmidt & Partner',
    balkon: true,
    kfwStandard: 'KfW 40 NH',
    extras: [],
  },
  {
    id: 'e10',
    projektId: 'p2',
    bezeichnung: 'WE A03 – 2.OG',
    typ: 'wohnung',
    etage: 2,
    zimmer: 3,
    flaeche: 74.5,
    kaufpreis: 278000,
    kaltmiete: 1050,
    status: 'verfuegbar',
    balkon: true,
    kfwStandard: 'KfW 40 NH',
    extras: [
      { id: 'ex10', typ: 'tiefgarage', bezeichnung: 'Tiefgaragenstellplatz TG-A03', preis: 19500, verfuegbar: true },
    ],
  },
  {
    id: 'e11',
    projektId: 'p2',
    bezeichnung: 'WE B01 – 1.OG',
    typ: 'wohnung',
    etage: 1,
    zimmer: 4,
    flaeche: 95.0,
    kaufpreis: 355000,
    kaltmiete: 1380,
    status: 'verfuegbar',
    balkon: true,
    kfwStandard: 'KfW 40 NH',
    extras: [
      { id: 'ex11', typ: 'tiefgarage', bezeichnung: 'Tiefgaragenstellplatz TG-B01', preis: 19500, verfuegbar: true },
      { id: 'ex12', typ: 'keller', bezeichnung: 'Kellerabteil K-B01', preis: 4000, verfuegbar: true },
    ],
  },
  {
    id: 'e12',
    projektId: 'p2',
    bezeichnung: 'WE B02 – 2.OG',
    typ: 'wohnung',
    etage: 2,
    zimmer: 2,
    flaeche: 62.0,
    kaufpreis: 232000,
    kaltmiete: 920,
    status: 'verkauft',
    balkon: true,
    kfwStandard: 'KfW 40 NH',
    extras: [],
  },
  // Projekt 3 – Parkresidenz Gohlis (Planung – noch keine Reservierungen)
  {
    id: 'e13',
    projektId: 'p3',
    bezeichnung: 'WE 1 – EG mit Garten',
    typ: 'wohnung',
    etage: 0,
    zimmer: 3,
    flaeche: 88.0,
    kaufpreis: 335000,
    kaltmiete: 1250,
    status: 'in_bau',
    balkon: false,
    kfwStandard: 'KfW 40 EE',
    extras: [
      { id: 'ex13', typ: 'stellplatz', bezeichnung: 'Außenstellplatz SP-1', preis: 10000, verfuegbar: true },
    ],
  },
  {
    id: 'e14',
    projektId: 'p3',
    bezeichnung: 'WE 2 – 1.OG',
    typ: 'wohnung',
    etage: 1,
    zimmer: 2,
    flaeche: 65.0,
    kaufpreis: 248000,
    kaltmiete: 950,
    status: 'in_bau',
    balkon: true,
    kfwStandard: 'KfW 40 EE',
    extras: [],
  },
];

export const kunden: Kunde[] = [
  {
    id: 'k1',
    vorname: 'Thomas',
    nachname: 'Bergmann',
    email: 'thomas.bergmann@email.de',
    telefon: '0151 2345 6789',
    segment: 'kapitalanleger',
    familienstand: 'verheiratet',
    einkommen: 95000,
    eigenkapital: 80000,
    steuersatz: 42,
    notizen: 'Sucht 2-3 Wohnungen als Altersvorsorge. Präferiert Leipzig. Gutes Netzwerk in der Pharmabranche.',
    angelegt: '2025-10-15',
    aktivitaeten: [
      { id: 'a1', kundeId: 'k1', datum: '2025-10-15', typ: 'telefonat', notiz: 'Erstkontakt über Empfehlung von Hr. Weber. Interesse an Kapitalanlage in Leipzig.' },
      { id: 'a2', kundeId: 'k1', datum: '2025-11-02', typ: 'termin', notiz: 'Besichtigung Stadtpark-Projekt. Sehr interessiert an WE 03 und WE 05. Möchte Steuerrechnung sehen.' },
      { id: 'a3', kundeId: 'k1', datum: '2025-11-10', typ: 'email', notiz: 'Steuerberechnung verschickt. Positive Rückmeldung. Nächstes Gespräch: 20.11.' },
    ],
  },
  {
    id: 'k2',
    vorname: 'Sandra',
    nachname: 'Hoffmann',
    email: 's.hoffmann@kanzlei-hoffmann.de',
    telefon: '0170 9876 5432',
    segment: 'kapitalanleger',
    familienstand: 'ledig',
    einkommen: 145000,
    eigenkapital: 200000,
    steuersatz: 45,
    notizen: 'Rechtsanwältin, sehr erfahren in Immobilieninvestitionen. Sucht Premium-Segment. Zeitknapp, klare Kommunikation bevorzugt.',
    angelegt: '2025-09-03',
    aktivitaeten: [
      { id: 'a4', kundeId: 'k2', datum: '2025-09-03', typ: 'termin', notiz: 'Erstgespräch. Sucht 1-2 Objekte 300k+ als Steueroptimierung.' },
      { id: 'a5', kundeId: 'k2', datum: '2025-09-20', typ: 'email', notiz: 'Exposé Penthouse (WE 07) zugesandt.' },
      { id: 'a6', kundeId: 'k2', datum: '2025-10-05', typ: 'telefonat', notiz: 'Penthouse sehr interessant. Fragt nach Reservierungsmöglichkeit.' },
    ],
  },
  {
    id: 'k3',
    vorname: 'Marcus',
    nachname: 'Klein',
    email: 'm.klein@web.de',
    telefon: '0162 3456 7890',
    segment: 'kapitalanleger',
    familienstand: 'verheiratet',
    einkommen: 72000,
    eigenkapital: 40000,
    steuersatz: 35,
    notizen: 'Erstinvestor, etwas zurückhaltend. Möchte Risiko minimieren. Gute Begleitung wichtig.',
    angelegt: '2025-11-20',
    aktivitaeten: [
      { id: 'a7', kundeId: 'k3', datum: '2025-11-20', typ: 'telefonat', notiz: 'Kaltakquise. Interessiert, aber noch viele Fragen. Termin vereinbart.' },
    ],
  },
  {
    id: 'k4',
    vorname: 'Lena',
    nachname: 'Schreiber',
    email: 'lena.schreiber@startup.io',
    telefon: '0178 1122 3344',
    segment: 'eigennutzer',
    familienstand: 'ledig',
    einkommen: 58000,
    eigenkapital: 35000,
    steuersatz: 30,
    notizen: 'Sucht Erstwohnung in Leipzig. Muss 2026 einziehen (Mietvertrag läuft aus). EG mit Garten wäre ideal.',
    angelegt: '2025-12-01',
    aktivitaeten: [
      { id: 'a8', kundeId: 'k4', datum: '2025-12-01', typ: 'termin', notiz: 'Besichtigung Stadtpark-Projekt. Sehr angetan von WE 01.' },
      { id: 'a9', kundeId: 'k4', datum: '2025-12-05', typ: 'telefonat', notiz: 'Finanzierungsbestätigung von der Bank liegt vor. Will zeitnah entscheiden.' },
    ],
  },
];

export const opportunities: Opportunity[] = [
  {
    id: 'o1',
    kundeId: 'k1',
    bezeichnung: 'Bergmann – 2x Leipzig Stadtpark',
    phase: 'angebot',
    positionen: [
      { einheitId: 'e3', extrasIds: ['ex4', 'ex5'] },
      { einheitId: 'e5', extrasIds: ['ex6'] },
    ],
    gesamtwert: 229000 + 18500 + 3500 + 235000 + 18500,
    zieldatum: '2026-02-28',
    notizen: 'Steuerrechnung verschickt. Wartet auf Rückmeldung Steuerberater.',
    erstellt: '2025-11-02',
    aktualisiert: '2025-11-10',
  },
  {
    id: 'o2',
    kundeId: 'k2',
    bezeichnung: 'Hoffmann – Penthouse Stadtpark',
    phase: 'reservierung',
    positionen: [
      { einheitId: 'e7', extrasIds: ['ex7', 'ex8'] },
    ],
    gesamtwert: 498000 + 21000 + 21000,
    zieldatum: '2026-01-31',
    notizen: 'Reservierung läuft. Notartermin für Januar angestrebt.',
    erstellt: '2025-10-05',
    aktualisiert: '2025-11-15',
  },
  {
    id: 'o3',
    kundeId: 'k3',
    bezeichnung: 'Klein – Einstieg Quartier Westend',
    phase: 'qualifizierung',
    positionen: [
      { einheitId: 'e10', extrasIds: ['ex10'] },
    ],
    gesamtwert: 278000 + 19500,
    zieldatum: '2026-04-30',
    notizen: 'Erstinvestor – braucht viel Begleitung. Steuerrechner zeigen.',
    erstellt: '2025-11-20',
    aktualisiert: '2025-11-22',
  },
  {
    id: 'o4',
    kundeId: 'k4',
    bezeichnung: 'Schreiber – EG Stadtpark (Eigennutz)',
    phase: 'erstgespraech',
    positionen: [
      { einheitId: 'e1', extrasIds: ['ex1', 'ex2'] },
    ],
    gesamtwert: 218000 + 18500 + 3500,
    zieldatum: '2026-03-31',
    notizen: 'Finanzierung steht. Entscheidung zeitnah erwartet.',
    erstellt: '2025-12-01',
    aktualisiert: '2025-12-05',
  },
];
